name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    # runs-on: [aws-ec2]
    runs-on: self-hosted
    needs: build
    steps:
      - name: Login to Docker Hub (again, in EC2)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Stop and Remove Old Container (if exists)
        run: |
          docker ps -q --filter "name=backend-container" | grep -q . && docker stop backend-container && docker rm backend-container || echo "No old container found."

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name backend-container ${{ secrets.DOCKER_USERNAME }}/backend:latest
