name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t backend .
      - name: Publish image to docker hub
        run: docker push backend:latest

  deploy:
    runs-on: [aws-ec2]
    needs: build
    steps:
      - name: Pull image from docker hub
        run: docker pull backend:latest
      - name: Delete old container
        run: docker rm -f backend-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 -name backend-container backend